notice: |
    This template is created by skyblue. in 2014/03/15
    You need to change setting in conf/app.conf, 
    And create a mysql database before you use -bee run- to start it.
file-rename:
  user_router.go: "{{.Table}}.go"
  controllers/user.go: controllers/{{.Table}}.go
  models/user.go: models/{{.Table}}.go
string-rename:
  User: "{{.Table|title}}"
