<!DOCTYPE html>
<html>
  	<head>
    	<title>RestAPI gogen</title>
    	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	</head>
  	<body>
		<h1>template rest<small>generated by gogen</small></h1>
		author: {{.Author}}
	</body>
</html>
